name: Deploy Production
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/**"
    branches:
      - "main"

jobs:
  BuildAndPublish:
    name: Build and Publish Production
    runs-on: ubuntu-22.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://npm.pkg.github.com"
      - name: Clean Yarn Cache
        run: yarn cache clean --all
      - name: Install dependencies
        run: yarn install
      - name: Clean dist directory
        run: rm -rf dist
      - name: Build
        run: npm run build
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GH_TOKEN }}
